field.formatter.settings.un_date_datetime:
  type: mapping
  label: 'Datetime default display format settings'
  mapping:
    display_timezone:
      type: boolean
      label: 'Display timezone'
    month_format:
      type: string
      label: 'Month format'
field.formatter.settings.un_date_daterange:
  type: mapping
  label: 'Datetime default display format settings'
  mapping:
    display_timezone:
      type: boolean
      label: 'Display timezone'
    month_format:
      type: string
      label: 'Month format'
field.formatter.settings.un_date_daterange_timezone:
  type: mapping
  label: 'Datetime default display format settings'
  mapping:
    display_timezone:
      type: boolean
      label: 'Display timezone'
    month_format:
      type: string
      label: 'Month format'
field.formatter.settings.un_data_date_recur_basic:
  type: mapping
  label: 'Datetime default display format settings'
  mapping:
    display_timezone:
      type: boolean
      label: 'Display timezone'
    month_format:
      type: string
      label: 'Month format'
